version: '3.4' 
networks:
    net:
services:
  search-api: # Spark API
    image: search-api
    container_name: search-api 
    ports:
      - 4567:4567
    networks:
      - net
    depends_on: 
      - solr-master
  solr-master: # Solr master
    image: solr-master
    container_name: solr-master
    ports:
      - 8983:8983
    networks:
      - net 
