FROM solr
LABEL maintainer="jovanibrasil@gmail.com"

USER root   
    # Set database environment variables
    ARG BLOG_MYSQL_URL 
    ARG BLOG_MYSQL_USERNAME 
    ARG BLOG_MYSQL_PASSWORD
	ENV DB_URL=$BLOG_MYSQL_URL
	ENV USER_NAME=$BLOG_MYSQL_USERNAME
	ENV PASSWORD=$BLOG_MYSQL_PASSWORD
    RUN echo 'SOLR_OPTS="$SOLR_OPTS -Ddb.url=$DB_URL -Ddb.user_name=$USER_NAME -Ddb.password=$PASSWORD"' >> /opt/solr/bin/solr.in.sh

USER solr
    RUN mkdir -p /opt/solr/temp
    COPY config-files /opt/solr/temp
    COPY mysql-connector/mysql-connector-java-8.0.15.jar /opt/solr/dist
    
# Create an core using pre-defined configurations
ENTRYPOINT [ "bash", "-c", "precreate-core blog /opt/solr/temp; exec solr -f" ]